steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/score-notifier-429122/image-registry/ms-users",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/score-notifier-429122/image-registry/ms-users",
      ]

logsBucket: 'CLOUD_LOGGING_ONLY'
serviceAccount: '665990681956-compute@developer.gserviceaccount.com'