version: "3"

services:
  db-users:
    container_name: users_database
    image: mysql:8.4.1
    restart: always
    volumes:
      - users-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=users_db

volumes:
  users-mysql-data: